### ISSUE TITLE
create and upload to staging html for six Arabic language licenses

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/3.0-IGO-Port-Official-Translations-and-Adoptions#1]

**Comment by mattl** [comment]
@peterspdx I'm thinking we did this...

**Comment by peterspdx** [comment]
where are those posted? just checking before we close this issue.

**Comment by rheaplex** [comment]
@mattl ^

**Comment by peterspdx** [comment]
Let's close this issue. We have heard nothing from the IGOs in at least a year that these are useful in translated languages, and we know that WIPO no longer has someone dedicated to assisting us manage the translations into other languages.
